model:
  name: "Mozhi"
  description: "English to Tamil Translator"
  parameters:
    dim_model: 512
    d_ff: 2048
    src_vocab_size: 32000
    tgt_vocab_size: 32000
    num_heads: 8
    num_layers: 6
    dropout: 0.1
    src_seq_len: 512
    tgt_seq_len: 512

