model:
  name: "Mozhi"
  description: "English to Tamil Translator"
  hyperparameters:
    dim_model: 512
    d_ff: 2048
    src_vocab_size: 32000
    tgt_vocab_size: 32000
    num_heads: 8
    num_layers: 6
    dropout: 0.1
    src_max_len: 512
    tgt_max_len: 512

